[package]
name = "ghoti-tuner"
version = "0.1.0"
edition = "2021"

[dependencies]
eval = { path = "../eval", package = "ghoti-eval" }
bot = { path = "../bot", package = "ghoti-bot" }
simulator = { path = "../simulator", package = "ghoti-simulator" }
rand = "0.8.5"
